apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "crm-lead-integration"
  description: "boilerplate para terceiros fazerem integracoes"
  annotations:
    github.com/project-slug: 'olxbr/crm-lead-integration'
    backstage.io/techdocs-ref: dir:.
    graph.microsoft.com/group-id: 6f449bce-ebc8-41bb-89b5-b965014a592c
    teams.olxbr.io/cloud-cost-center: 24b102ae-bb4c-46a8-b466-ccaa5863e49e
    olxbr.io/critical: 'false'
    olxbr.io/dora: squad-olx-ads-experience
    sonarqube.org/project-key: olxbr_crm-lead-integration
    olxbr.io/bcp-ready: 'false'
  tags:
    - do-do-squad-atributos-e-seguranca
    - dj-ic
  links:
    - url: 'https://olxbrasil.slack.com/archives/C04670X6YF2'
      title: '#slack-channel'
      icon: chat
      type: api
spec:
  type: library
  owner: group:default/squad-olx-integrations
  lifecycle: production
