name: Pull Request
on: [pull_request]
jobs:
  run_tests:
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running build and test for ${{ github.ref }} branch"

      - name: Quality Gate - Unit Test
        run: true
